package com.example.yugioh

enum class Card_Type(val type:String) {
   NORMAL_Card("Normal Monster"),
    NORMAL_TUNER_Card("Normal Tuner Monster"),
    EFFECT_Card("Effect Monster"),
    TUNER_Card("Tuner Monster"),
    FLIP_Card("Flip Monster"),
    FLIP_EFFECT_Card("Flip Effect Monster"),
    FLIP_TUNER_EFFECT_Card("Flip Tuner Effect Monster"),
    SPIRIT_Card("Spirit Monster"),
    UNION_EFFECT_Card("Union Effect Monster"),
    GEMINI_Card("Gemini Monster"),
    PENDALUM_Card("Pendulum Effect Monster"),
    PENDALUM_NORMAL_Card("Pendulum Normal Monster"),
    PENDALUM_TUNER_EFFECT_Card("Pendulum Tuner Effect Monster"),
    RITUAL_Card("Ritual Monster"),
    RITUAL_EFFECT_Card("Ritual Effect Monster"),
    TOON_Card("Toon Monster"),
    FUSION_Card("Fusion Monster"),
    SYNCHRO_Card("Synchro Monster"),
    SYNCHRO_TUNER_Card("Synchro Tuner Monster"),
    SYNCHRO_PENDULUM_EFFECT_Card("Synchro Pendulum Effect Monster"),
    XYZ_Card("XYZ Monster"),
    XYZ_PENDALUM_EFFECT_Card("XYZ Pendulum Effect Monster"),
    LINK_Card("Link Monster"),
    PENDALUM_FLIP_EFFECT_Card("Pendulum Flip Effect Monster"),
        PENDALUM_EFFECT_FUSION_Card("Pendulum Effect Fusion Monster"),
    TOKEN("Token"),
 SKILL_CARD("Skill Card"),
 SPELL_CARD("Spell Card"),
 TRAP_CARD("Trap Card"),
 NONE("")
}